name: Build APK

env:
  main_project_module: app
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set hash as env variable
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Write key
        if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/main' ) }}
        run: |
            if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
              {
                echo KEYSTORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
                echo KEY_ALIAS='${{ secrets.KEY_ALIAS }}'
                echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}'
                echo KEYSTORE_FILE='key.jks'
              } >> gradle.properties
              echo ${{ secrets.KEYSTORE }} | base64 -d > key.jks
            fi

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build gradle project
        run: ./gradlew build

      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble

      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug

      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repository_name }}-${{ env.hash }}-release
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repository_name }}-${{ env.hash }}-debug
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repository_name }}-${{ env.hash }}-AAB
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/